<a href="https://colab.research.google.com/github/z-serra/PythonNotes4ML/blob/main/NLPNotes2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('reviews.tsv', delimiter = '\t', quoting = 3)

import re
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
corpus = []

for i in range(0, 1000):

  review = re.sub('[^a-zA-Z]', ' ', df['Review'][i])
  review = review.lower()
  review = review.split()

  ps = PorterStemmer()

  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')

  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[55 42]
 [12 91]]


0.73

In [3]:
new_review = 'I love the food in here'
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
classifier.predict(new_X_test)

array([1])

In [4]:
new_review = 'Food was bad'
new_review = re.sub('[^a-zA-Z]', ' ', new_review)
new_review = new_review.lower()
new_review = new_review.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review = ' '.join(new_review)
new_corpus = [new_review]
new_X_test = cv.transform(new_corpus).toarray()
classifier.predict(new_X_test)

array([0])

## Homework - Model Selection

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "kNN": KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2),
    "SVM (Linear)": SVC(kernel='linear'),
    "Kernel SVM (RBF)": SVC(kernel='rbf'),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(criterion='entropy'),
    "Random Forest": RandomForestClassifier(n_estimators=10, criterion='entropy'),
}

# results
for name, model in models.items():

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{name}:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1:", f1_score(y_test, y_pred))
    print("-" * 40)

Logistic Regression:
Accuracy: 0.775
Precision: 0.8152173913043478
Recall: 0.7281553398058253
F1: 0.7692307692307693
----------------------------------------
kNN:
Accuracy: 0.64
Precision: 0.7012987012987013
Recall: 0.5242718446601942
F1: 0.6
----------------------------------------
SVM (Linear):
Accuracy: 0.8
Precision: 0.8181818181818182
Recall: 0.7864077669902912
F1: 0.801980198019802
----------------------------------------
Kernel SVM (RBF):
Accuracy: 0.775
Precision: 0.8918918918918919
Recall: 0.6407766990291263
F1: 0.7457627118644068
----------------------------------------
Naive Bayes:
Accuracy: 0.73
Precision: 0.6842105263157895
Recall: 0.883495145631068
F1: 0.7711864406779662
----------------------------------------
Decision Tree:
Accuracy: 0.74
Precision: 0.7931034482758621
Recall: 0.6699029126213593
F1: 0.7263157894736842
----------------------------------------
Random Forest:
Accuracy: 0.73
Precision: 0.855072463768116
Recall: 0.5728155339805825
F1: 0.686046511627907
------