<a href="https://colab.research.google.com/github/z-serra/PythonNotes4ML/blob/main/NumPyNotes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# arange

np.arange(0, 10, 2) # start stop step

array([0, 2, 4, 6, 8])

In [5]:
# zeros

np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# ones

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# linspace

np.linspace(0, 5, 10) # 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [9]:
# eye

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# random rand

np.random.rand(5) # 5 random numbers uniformly distributed from 0 to 1

array([0.26417835, 0.44179988, 0.21266217, 0.03544833, 0.27714868])

In [11]:
np.random.rand(5, 5)

array([[0.33565353, 0.87987266, 0.4015539 , 0.33569133, 0.15699744],
       [0.44070259, 0.27546901, 0.53622168, 0.6798589 , 0.83780754],
       [0.89067774, 0.97431628, 0.13156199, 0.78157159, 0.30256027],
       [0.35385753, 0.97492031, 0.60661826, 0.1247535 , 0.89325376],
       [0.06441945, 0.74814904, 0.10310481, 0.17554538, 0.20357571]])

In [12]:
# random randn

np.random.randn(5) # standard normal distribution center around 0

array([ 0.33213508, -0.28502956,  2.24934517,  0.62081411,  0.20541592])

In [13]:
# random randint

np.random.randint(1, 101)

53

In [14]:
np.random.randint(1, 101, 10)

array([87, 23, 76, 94, 92, 80, 16, 65, 97, 26])

In [15]:
# reshape

np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
arr_1 = np.random.randint(1, 101, 10)
arr_1

array([24, 85, 43, 96, 96, 52, 42, 84, 87, 43])

In [18]:
# max

arr_1.max()

np.int64(96)

In [19]:
# min

arr_1.min()

np.int64(24)

In [20]:
# argmax

arr_1.argmax()

np.int64(3)

In [21]:
# argmin

arr_1.argmin()

np.int64(0)

In [22]:
# shape

arr_1.shape

(10,)

In [23]:
arr_1 = arr_1.reshape(2, 5)

In [24]:
arr_1.shape

(2, 5)

In [25]:
# dtype

arr_1.dtype

dtype('int64')

In [26]:
arr_1 = arr_1.reshape(10)
arr_1

array([24, 85, 43, 96, 96, 52, 42, 84, 87, 43])

In [27]:
arr_1[0:4] = 100
arr_1

array([100, 100, 100, 100,  96,  52,  42,  84,  87,  43])

In [28]:
# mutating a slice of the original array also changes the original array
arr_1 = np.random.randint(1, 101, 10)
arr_1_slice = arr_1[0:4]
arr_1_slice[:] = 100
arr_1

array([100, 100, 100, 100,  94,  88,  29,  80,  10,  87])

In [29]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [30]:
arr_2d[1, 2]

np.int64(6)

In [31]:
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [32]:
# comparison
np.arange(11) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [33]:
# conditional selection

np.arange(11)[np.arange(11) > 5]

array([ 6,  7,  8,  9, 10])

In [34]:
np.arange(11) + np.arange(11)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.arange(11) * np.arange(11)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [36]:
np.arange(11) / np.arange(11)

/tmp/ipykernel_6102/942368168.py:1: RuntimeWarning: invalid value encountered in divide
  np.arange(11) / np.arange(11)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
1 / np.arange(11)

/tmp/ipykernel_6102/3842780974.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / np.arange(11)


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [38]:
# sqrt

np.sqrt(np.arange(11))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [39]:
# exp

np.exp(np.arange(11))

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [40]:
# max

np.max(np.arange(11))

np.int64(10)

In [41]:
# min

np.min(np.arange(11))

np.int64(0)

In [42]:
# sin

np.sin(np.arange(11))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [43]:
# cos

np.cos(np.arange(11))

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [44]:
# log

np.log(np.arange(11))

/tmp/ipykernel_6102/1131522100.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(np.arange(11))


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [45]:
# sum

np.sum(np.arange(11))

np.int64(55)

In [46]:
np.arange(11).sum()

np.int64(55)

In [47]:
# std

np.std(np.arange(11))

np.float64(3.1622776601683795)

In [48]:
np.arange(11).std()

np.float64(3.1622776601683795)

In [49]:
# sum of cols

np.arange(10).reshape(2, 5).sum(axis=0)

array([ 5,  7,  9, 11, 13])